MKSHELL="/bin/bash"

#target: OPCIONES: prereq
# La opcion Q = QUIET no imprime todo

#target:OPCIONES:prereq
#./test/data/final.vcf: ./test/data/final.txt ./test/data/positions.txt

%.bam: %.sam
	echo "[DEBUG] Running analysis"
	samtools view -S -b $prereq | samtools sort - > $target \
	&& samtools index $target  
